# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nlpost_gomp <- function(param, data) {
    .Call('iLaplace_nlpost_gomp', PACKAGE = 'iLaplace', param, data)
}

grad_gomp <- function(param, data) {
    .Call('iLaplace_grad_gomp', PACKAGE = 'iLaplace', param, data)
}

hess_gomp <- function(param, data) {
    .Call('iLaplace_hess_gomp', PACKAGE = 'iLaplace', param, data)
}

nlDen_mvt <- function(x, m, df) {
    .Call('iLaplace_nlDen_mvt', PACKAGE = 'iLaplace', x, m, df)
}

nlDen_mvskt <- function(x, a, c, m, df) {
    .Call('iLaplace_nlDen_mvskt', PACKAGE = 'iLaplace', x, a, c, m, df)
}

grad_mvt <- function(x, m, df) {
    .Call('iLaplace_grad_mvt', PACKAGE = 'iLaplace', x, m, df)
}

grad_mvskt <- function(x, a, c, m, df) {
    .Call('iLaplace_grad_mvskt', PACKAGE = 'iLaplace', x, a, c, m, df)
}

hess_mvt <- function(x, m, df) {
    .Call('iLaplace_hess_mvt', PACKAGE = 'iLaplace', x, m, df)
}

hess_mvskt <- function(x, a, c, m, df) {
    .Call('iLaplace_hess_mvskt', PACKAGE = 'iLaplace', x, a, c, m, df)
}

dmvt <- function(x, mu, S, p, df, lg) {
    .Call('iLaplace_dmvt', PACKAGE = 'iLaplace', x, mu, S, p, df, lg)
}

dhalfCauchy <- function(x, scale, lg = FALSE) {
    .Call('iLaplace_dhalfCauchy', PACKAGE = 'iLaplace', x, scale, lg)
}

rmvnorm <- function(mu, S, p) {
    .Call('iLaplace_rmvnorm', PACKAGE = 'iLaplace', mu, S, p)
}

rmvt <- function(mu, S, p, df) {
    .Call('iLaplace_rmvt', PACKAGE = 'iLaplace', mu, S, p, df)
}

prJeff <- function(nu, lg = FALSE) {
    .Call('iLaplace_prJeff', PACKAGE = 'iLaplace', nu, lg)
}

grldmvt <- function(x, mu, S, p, df) {
    .Call('iLaplace_grldmvt', PACKAGE = 'iLaplace', x, mu, S, p, df)
}

hessldmvt <- function(x, mu, S, p, df) {
    .Call('iLaplace_hessldmvt', PACKAGE = 'iLaplace', x, mu, S, p, df)
}

nlpost_lub <- function(beta, lsig, y, x1, x2, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplace_nlpost_lub', PACKAGE = 'iLaplace', beta, lsig, y, x1, x2, n, muBeta, SigBeta, sigScale)
}

nlpostT_lub <- function(beta, lsig, lnu, y, x1, x2, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplace_nlpostT_lub', PACKAGE = 'iLaplace', beta, lsig, lnu, y, x1, x2, n, muBeta, SigBeta, sigScale)
}

grad_lub <- function(beta, lsig, y, x1, x2, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplace_grad_lub', PACKAGE = 'iLaplace', beta, lsig, y, x1, x2, n, muBeta, SigBeta, sigScale)
}

gradT_lub <- function(beta, lsig, lnu, y, x1, x2, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplace_gradT_lub', PACKAGE = 'iLaplace', beta, lsig, lnu, y, x1, x2, n, muBeta, SigBeta, sigScale)
}

hess_lub <- function(beta, lsig, y, x1, x2, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplace_hess_lub', PACKAGE = 'iLaplace', beta, lsig, y, x1, x2, n, muBeta, SigBeta, sigScale)
}

hessT_lub <- function(beta, lsig, lnu, y, x1, x2, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplace_hessT_lub', PACKAGE = 'iLaplace', beta, lsig, lnu, y, x1, x2, n, muBeta, SigBeta, sigScale)
}

MCMCmetrop_cpp <- function(lfun, start, V, mcmc, burnin, df, verbose, myframe) {
    .Call('iLaplace_MCMCmetrop_cpp', PACKAGE = 'iLaplace', lfun, start, V, mcmc, burnin, df, verbose, myframe)
}

mlChib_cpp <- function(lfun, hatPar, V, mcmc, df, verbose, myframe) {
    .Call('iLaplace_mlChib_cpp', PACKAGE = 'iLaplace', lfun, hatPar, V, mcmc, df, verbose, myframe)
}

mlIS_cpp <- function(lfun, hatPar, V, nsim, p, df, verbose, myframe) {
    .Call('iLaplace_mlIS_cpp', PACKAGE = 'iLaplace', lfun, hatPar, V, nsim, p, df, verbose, myframe)
}

nlpost_bod2 <- function(beta, lsig, y, x, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplace_nlpost_bod2', PACKAGE = 'iLaplace', beta, lsig, y, x, n, muBeta, SigBeta, sigScale)
}

nlpostT_bod2 <- function(beta, lsig, lnu, y, x, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplace_nlpostT_bod2', PACKAGE = 'iLaplace', beta, lsig, lnu, y, x, n, muBeta, SigBeta, sigScale)
}

grad_bod2 <- function(beta, lsig, y, x, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplace_grad_bod2', PACKAGE = 'iLaplace', beta, lsig, y, x, n, muBeta, SigBeta, sigScale)
}

hess_bod2 <- function(beta, lsig, y, x, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplace_hess_bod2', PACKAGE = 'iLaplace', beta, lsig, y, x, n, muBeta, SigBeta, sigScale)
}

gradT_bod2 <- function(beta, lsig, lnu, y, x, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplace_gradT_bod2', PACKAGE = 'iLaplace', beta, lsig, lnu, y, x, n, muBeta, SigBeta, sigScale)
}

hessT_bod2 <- function(beta, lsig, lnu, y, x, n, muBeta, SigBeta, sigScale) {
    .Call('iLaplace_hessT_bod2', PACKAGE = 'iLaplace', beta, lsig, lnu, y, x, n, muBeta, SigBeta, sigScale)
}

seqMat <- function(par, se, lengthOut, q, delta) {
    .Call('iLaplace_seqMat', PACKAGE = 'iLaplace', par, se, lengthOut, q, delta)
}

nlogH <- function(randPar, fixPar, data) {
    .Call('iLaplace_nlogH', PACKAGE = 'iLaplace', randPar, fixPar, data)
}

grad_nlogH <- function(randPar, fixPar, data) {
    .Call('iLaplace_grad_nlogH', PACKAGE = 'iLaplace', randPar, fixPar, data)
}

hess_nlogH <- function(randPar, fixPar, data) {
    .Call('iLaplace_hess_nlogH', PACKAGE = 'iLaplace', randPar, fixPar, data)
}

ldetHess_nlogH <- function(randPar, fixPar, data) {
    .Call('iLaplace_ldetHess_nlogH', PACKAGE = 'iLaplace', randPar, fixPar, data)
}

